### PR TITLE
Added new resource sizes for iPad Pro and for iPhone Plus.

### PR DESCRIPTION
**Pull request by jthoms1**
This pull request should correct iPad pro issues. As well as include appropriately sized iPhone Plus.
fixes driftyco/ionic-cli#713
fixes driftyco/ionic-cli#870

### CODE REVIEW

**Comment by tlancina** [comment]
Looks good to me :+1:

**Comment by ArjenBroeze** [comment]
New to this. So how do I use this, do I need to update ionic or its libs or what?

**Comment by emilyemorehouse** [comment]
@jthoms1, do you have any info you can provide on how to use the splash images you added for iPad Pro? Everything I found said that xcassets didn't have slots for iPad Pro and that you had to use a storyboard instead.

**Comment by jthoms1** [comment]
Hey @emilyemorehouse we don't have a good way of using these images right now. 
It appears that there is an open issue with Cordova. https://issues.apache.org/jira/browse/CB-9762

**Comment by DavidFrahm** [comment]
How can I get an ionic-cli that has this fix?

Looking at ionic-cli releases it seems it has not pulled in a new Ionic-app-lib in a while.

**Pull request merged**
