### PR TITLE
Update info.js

### PR DESCRIPTION
**Pull request by domhnallw**
Fixed OS version reporting for Mac OS X. Data sourced from Wikipedia.

### CODE REVIEW

**Comment by tlancina** [comment]
Thanks for the PR! What if we just take the first two digits of the version for the switch? Slightly more future proof for El Capitan if a new OS X name comes out.

**Comment by domhnallw** [comment]
It would be easier to do it the way you suggest, but I was trying to change as little as possible...

**Comment by tlancina** [comment]
@domhnallw no worries, if you'd prefer I can merge it in so it works and then tweak it.

**Comment by domhnallw** [comment]
Give me a minute, I'll trim it back a bit.

**Comment by domhnallw** [comment]
@tlancina How about that? Should be valid based on how Apple do things?

**Comment by tlancina** [comment]
Looks great, thank you!

**Comment by domhnallw** [comment]
Nice one, thanks!

**Pull request merged**
