### PR TITLE
fix(info): add windows 10 detection to the info module

### PR DESCRIPTION
**Pull request by jthoms1**
This pull request will add detection of windows 10.

### CODE REVIEW

**Comment by tlancina** [comment]
Looks good to me, my question is - where does this number come from? We can make a note of it in the merge commit in case it needs to be updated.

**Comment by jthoms1** [comment]
Actually we should probably just use the first 2 numbers to identify the OS version name. https://msdn.microsoft.com/en-us/library/windows/desktop/ms724832(v=vs.85).aspx

I will probably change in favor of using https://www.npmjs.com/package/os-name.

**Comment by jthoms1** [comment]
I left getMacInfo and getWindowsEnvironmentInfo in place because they could be used outside of app-lib.

**Comment by jthoms1** [comment]
We are now using os-names and will not track windows versions within the app code.

**Pull request closed without merging**
