### PR TITLE
fix(resources): adds icon for iPad Pro, removes unused icon-60

### PR DESCRIPTION
**Pull request by emilyemorehouse**
fixes driftyco/ionic-cli#713
fixes driftyco/ionic-cli#870

Updates for the resources command: iOS icons: fixes an unused image error and adds iPad Pro support.
- Removes icon-60.png, no longer required. 
- Generates an icon for iPad Pro, icon-83.5@2x.png at 167x167.

Fixing the splash screen issues will take more effort, as iPad Pro must use a storyboard instead of splash images.

### CODE REVIEW

**Comment by jthoms1** [comment]
@emilyemorehouse Thanks for the pull request!  Could you please add icon-60 back into the resource file? It is possible an older version of Xcode might still depend on this. Once completed I will merge.

**Comment by emilyemorehouse** [comment]
Do you still need this PR? Looks like it was fixed with driftyco/ionic-app-lib/pull/88

**Comment by tlancina** [comment]
Hey @emilyemorehouse sorry for the miscommunication, I just merged in @jthoms1 PR without realizing that the fix was in here. If it's a hassle don't worry about updating it, but we wanted you to still get credit for contributing :)

**Comment by emilyemorehouse** [comment]
Ah thanks, I appreciate that! Pushed a new commit to add the icon-60 back.

**Pull request merged**
