### PR TITLE
fix for 302s and cookies being lost

### PR DESCRIPTION
**Pull request by zambien**
Pull request from the issue below.  I can't take credit for the solution but would like to see this added.

https://github.com/driftyco/ionic-cli/issues/415#event-461419851

### CODE REVIEW

**Comment by onderceylan** [comment]
Why is this still open?

**Comment by Airblader** [comment]
@zambien @onderceylan Since this PR has been closed, what is the actual fix here? I still experience #415 and this PR does fix my issue. What's the alternative?

**Comment by zambien** [comment]
I had closed this because no one seemed interested in the fix and I felt it made sense to close it based upon @onderceylan's question.

I am glad to reopen it if it will be considered for a merge.

**Comment by Airblader** [comment]
#1226 has been merged, so this can be closed now.

**Pull request closed without merging**
